spring:
  mvc:
    path match:
      matching-strategy: ant_path_matcher
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: create
        default_batch_fetch_size: 1000
  mail:
    host: smtp.gmail.com
    port: 587
    username: surveyMateUMC5@gmail.com
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connection-timeout: 5000
          timeout: 5000

cloud:
  aws:
    s3:
      bucket: ${AWS_S3_BUCKET_NAME}
    credentials:
      access-key: ${AWS_ACCESS}
      secret-key: ${AWS_SECRET}
    region:
      static: ap-northeast-2
    stack:
      auto: false

jwt:
  secret: 1ecadcca6955d88702e5df3116ac2d4fef2fc50c3b8cea83d83abff1659b266dda01f142c76961878fdf6ba20fb6dbc35171a5db7976d2325e6a1a43057a0eef
  header: Authorization
  token-prefix: Bearer

server:
  port: ${PORT}