spring:
  mvc:
    path match:
      matching-strategy: ant_path_matcher
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: update
        default_batch_fetch_size: 1000

cloud:
  aws:
    s3:
      bucket: ${AWS_S3_BUCKET_NAME}
      path:
        data-file: data
    credentials:
      access-key: ${AWS_ACCESS}
      secret-key: ${AWS_SECRET}
    region:
      static: ap-northeast-2
    stack:
      auto: false

jwt:
  secret: ${JWT_SECRET_KEY}
  header: Authorization
  token-prefix: Bearer

server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  port: ${PORT}